const $=id=>document.getElementById(id); let state=null, noticeTimer;
const fmt=n=>Number(n).toLocaleString(); const money=n=>`${fmt(n)} Credits`; const time=s=>new Date(s).toLocaleString('zh-TW',{hour12:false});
function notify(text){$('notice').textContent=text;$('notice').classList.remove('hidden');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('notice').classList.add('hidden'),3500)}
async function api(path,options={}){const r=await fetch(path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const d=await r.json();if(!r.ok||d.ok===false)throw new Error(d.error||'Request failed');return d}
function renderPicker(users){$('userSelect').innerHTML=users.map(u=>`<option value="${u.id}">${u.displayName} (@${u.username})</option>`).join('')}
function render(){if(!state)return;$('credits').textContent=money(state.credits);$('userName').textContent=state.user.displayName;$('userHandle').textContent=`@${state.user.username} · ${state.user.role}`;$('inventoryValue').textContent=money(state.items.reduce((s,i)=>s+i.value*i.stock,0));$('collectionCount').textContent=state.holdings.length;
 $('marketGrid').innerHTML=state.items.filter(i=>i.status==='AVAILABLE').map(i=>`<article class="card"><img src="${i.img}" alt="${i.name}"><div class="card-body"><span class="tag">${i.category}</span><h3>${i.name}</h3><div class="meta"><b>${money(i.value)}</b><small>庫存 ${i.stock}</small></div><button class="primary full" ${i.stock<=0||state.credits<i.value?'disabled':''} onclick="redeem('${i.id}')">${i.stock<=0?'售罄':state.credits<i.value?'Credits 不足':'直接兌換'}</button></div></article>`).join('');
 $('collectionGrid').innerHTML=state.holdings.length?state.holdings.map(h=>`<article class="card"><img src="${h.img}" alt="${h.name}"><div class="card-body"><span class="tag">${h.status}</span><h3>${h.name}</h3><div class="meta"><b>${money(h.value)}</b><small>${h.category}</small></div><button class="ghost full" disabled>Steam 提取（預留）</button></div></article>`).join(''):'<div class="empty">目前沒有收藏品。</div>';
 $('ledgerBody').innerHTML=state.ledger.map(x=>`<tr><td>${time(x.createdAt)}</td><td>${x.kind}</td><td class="${x.amount>=0?'plus':'minus'}">${x.amount>=0?'+':''}${fmt(x.amount)}</td><td>${fmt(x.balance)}</td><td>${x.ref}</td></tr>`).join('')||'<tr><td colspan="5">尚無紀錄</td></tr>';
 $('txBody').innerHTML=state.transactions.map(x=>`<tr><td>${time(x.createdAt)}</td><td>${x.type}</td><td><span class="status">${x.status}</span></td><td>${fmt(x.amount)}</td><td>${x.ref}</td></tr>`).join('')||'<tr><td colspan="5">尚無紀錄</td></tr>';
 $('adminTab').classList.toggle('hidden',state.user.role!=='ADMIN'); if(state.user.role==='ADMIN') loadAdmin();
}
window.redeem=async itemId=>{try{const d=await api('/api/redeem',{method:'POST',body:JSON.stringify({itemId,requestId:crypto.randomUUID()})});state=d.state;render();notify(d.message)}catch(e){notify(e.message)}};
$('grant').onclick=async()=>{try{const d=await api('/api/credits/grant',{method:'POST'});state=d.state;render();notify(d.message)}catch(e){notify(e.message)}};
$('reset').onclick=async()=>{try{const d=await api('/api/reset',{method:'POST'});state=d.state;render();notify(d.message)}catch(e){notify(e.message)}};
$('logout').onclick=async()=>{await api('/api/auth/logout',{method:'POST'});location.reload()};
$('login').onclick=async()=>{try{const d=await api('/api/auth/dev-login',{method:'POST',body:JSON.stringify({userId:$('userSelect').value})});state=d.state;renderPicker(d.users);$('loginGate').classList.add('hidden');render();notify('登入成功')}catch(e){notify(e.message)}};

function handleSteamNotice(){
  const q=new URLSearchParams(location.search);
  if(q.get('steam_login')==='success') notify('Steam 登入成功');
  if(q.get('steam_error')){
    const map={session:'Steam 登入工作階段已過期，請重試。',cancelled:'你取消了 Steam 登入。',verification:'Steam 身分驗證失敗，請重試。'};
    notify(map[q.get('steam_error')]||'Steam 登入失敗。');
  }
  if(q.has('steam_login')||q.has('steam_error')) history.replaceState({},'',location.pathname);
}

async function loadAdmin(){try{const d=await api('/api/admin/state');const s=d.stats;$('adminRoot').innerHTML=`<div class="stat-grid"><div class="stat"><span>使用者</span><b>${s.users}</b></div><div class="stat"><span>有效使用者</span><b>${s.activeUsers}</b></div><div class="stat"><span>商品</span><b>${s.items}</b></div><div class="stat"><span>庫存參考值</span><b>${money(s.inventoryValue)}</b></div><div class="stat"><span>收藏</span><b>${s.holdings}</b></div><div class="stat"><span>待處理</span><b>${s.pending}</b></div></div><div class="admin-grid"><div class="panel"><h3>新增商品</h3><div class="form"><input id="aname" placeholder="商品名稱"><input id="acat" placeholder="分類"><input id="aval" type="number" placeholder="Credits"><input id="astock" type="number" placeholder="庫存"><input id="aimg" placeholder="圖片 URL（可留白）"><button class="primary" onclick="adminCreateItem()">建立商品</button></div></div><div class="panel"><h3>商品庫存</h3><div class="admin-list">${d.items.map(i=>`<div class="admin-row"><div><b>${i.name}</b><small>${i.category} · ${money(i.value)}</small></div><div class="row-actions"><input value="${i.stock}" id="stock_${i.id}" type="number" min="0"><button class="ghost" onclick="adminStock('${i.id}')">更新</button></div></div>`).join('')}</div></div></div><div class="panel"><h3>使用者</h3><div class="admin-list">${d.users.map(u=>`<div class="admin-row"><div><b>${u.displayName}</b><small>@${u.username} · ${u.role} · ${u.status}</small></div><div class="row-actions"><input id="credit_${u.id}" type="number" placeholder="±Credits"><button class="ghost" onclick="adminCredit('${u.id}')">調整</button>${u.role==='USER'?`<button class="danger" onclick="adminStatus('${u.id}','${u.status==='ACTIVE'?'SUSPENDED':'ACTIVE'}')">${u.status==='ACTIVE'?'停用':'恢復'}</button>`:''}</div></div>`).join('')}</div></div><div class="panel"><h3>最近交易</h3><div class="admin-list">${d.transactions.slice(0,30).map(t=>`<div class="admin-row"><div><b>${t.type}</b><small>${t.userId} · ${time(t.createdAt)}</small></div><div><span class="status">${t.status}</span> ${fmt(t.amount)} · ${t.ref}</div></div>`).join('')||'<div class="empty">尚無交易</div>'}</div></div>`}catch(e){$('adminRoot').innerHTML=`<div class="empty">${e.message}</div>`}}
window.adminCreateItem=async()=>{try{const d=await api('/api/admin/item',{method:'POST',body:JSON.stringify({name:$('aname').value,category:$('acat').value,value:Number($('aval').value),stock:Number($('astock').value),img:$('aimg').value})});notify('商品建立成功');await loadAdmin()}catch(e){notify(e.message)}};
window.adminStock=async id=>{try{await api('/api/admin/item/'+id,{method:'PATCH',body:JSON.stringify({stock:Number($('stock_'+id).value)})});notify('庫存已更新');await loadAdmin()}catch(e){notify(e.message)}};
window.adminCredit=async id=>{try{const amount=Number($('credit_'+id).value);if(!Number.isInteger(amount)||amount===0)return notify('請輸入整數 Credits');await api('/api/admin/credit',{method:'POST',body:JSON.stringify({userId:id,amount})});notify('Credits 已調整');await loadAdmin()}catch(e){notify(e.message)}};
window.adminStatus=async(id,status)=>{try{await api('/api/admin/user-status',{method:'POST',body:JSON.stringify({userId:id,status})});notify('使用者狀態已更新');await loadAdmin()}catch(e){notify(e.message)}};
$('refreshAdmin').onclick=loadAdmin;
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>{if(b.classList.contains('hidden'))return;document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active');if(b.dataset.tab==='admin')loadAdmin()});
(async()=>{handleSteamNotice();try{const u=await api('/api/auth/users');renderPicker(u.users);const d=await api('/api/state');state={user:d.user,credits:d.credits,items:d.items,holdings:d.holdings,ledger:d.ledger,transactions:d.transactions};$('loginGate').classList.add('hidden');render()}catch{ $('loginGate').classList.remove('hidden') }})();
